### ISSUE TITLE
Investigate replacing our custom polling of Lambda Runtime API 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#1024]
with: https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-runtime-interface-client#aws-lambda-java-runtime-interface-client

see: https://mark-sailes.medium.com/opening-sourcing-the-aws-java-runtime-interface-client-144ecdb70671

**Comment by sdelamo** [comment]
I have created a sample app to verify if we can use [AWS Lambda Java Runtime Interface Client](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-runtime-interface-client)

instead of [Micronaut AWS custom runtime](https://github.com/micronaut-projects/micronaut-aws/tree/master/function-aws-custom-runtime). 

I have added the GraalVM configuration in [AWS PR #235](https://github.com/aws/aws-lambda-java-libs/pull/235) by @msailes and [AWS PR #208](https://github.com/aws/aws-lambda-java-libs/pull/208) by @fafriat.

Related [issue #1024](https://github.com/micronaut-projects/micronaut-aws/issues/1024).

To generate ZIP file containing bootstrap and Native Image, run:

`./gradlew buildNativeImage`

```
Fatal error:java.lang.NoClassDefFoundError
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
Caused by: java.lang.NoClassDefFoundError: org/grails/datastore/mapping/validation/ValidationException
at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.getDeclaredMethods(Native Method)
at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:987)
at com.oracle.svm.jni.access.JNIAccessibleMethod.anyMatchIgnoreReturnType(JNIAccessibleMethod.java:139)
at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:103)
at com.oracle.svm.jni.access.JNIAccessibleMember.setHidingSubclasses(JNIAccessibleMember.java:83)
at com.oracle.svm.jni.access.JNIAccessibleMethod.finishBeforeCompilation(JNIAccessibleMethod.java:135)
at com.oracle.svm.jni.access.JNIAccessFeature.beforeCompilation(JNIAccessFeature.java:350)
at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:619)
at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:619)
at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: org.grails.datastore.mapping.validation.ValidationException
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 17 more
Error: Image build request failed with exit status 1
```

I don't think `--allow-incomplete-classpath` flag helps for JNI. See commented out Gradle task `addInitializeAtBuildTime`.  Any clue @ilopmar ?

**Comment by ilopmar** [comment]
The flag `--allow-incomplete-classpath` is already included in [micronaut-inject](https://github.com/micronaut-projects/micronaut-core/blob/4e35cd2e5eff534c8d6c9d82c115a97ee366a9e1/inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties#L17) so no need to add it again.

I don't know why the native image fails with `org.grails.datastore.mapping.validation.ValidationException` because in regular native images we only see a warning but the process finished ok: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1177748796#L68

After building locally Micronaut without `org.grails.datastore.mapping.validation.ValidationException` I've been down to the rabbit hole of adding more and more dependencies to be able to generate the native image without success. I went a step back and tried what we did last week with our own generated GraalVM configuration and I've discovered that [this JNI config](https://github.com/aws/aws-lambda-java-libs/pull/208/files#diff-af535ccd7ea41bbe3d3f5a9912052ffc12eb0569b7e37e4a967d346eb4cc463dR6-R10) triggers all the tcnative and related class not found.
So we are stuck here and maybe the GraalVM configuration is not the right one to be included by default or it's not for Micronaut.

**Comment by ilopmar** [comment]
@sdelamo I've done a few more tries. Last week we had this error when running in AWS:

```
10:56:49.626 [main] INFO i.m.context.env.DefaultEnvironment - Established active environments: [ec2, cloud, function, lambda]
Failed to load the native runtime interface client library /aws-lambda-runtime-interface-client.glibc.so. Exception: null
Failed to load the native runtime interface client library /aws-lambda-runtime-interface-client.musl.so. Exception: null
```

The error now is clear and what happens is that we need to include `glibc.so` and `musl.so` in the native image resources file:

```json
{
  "resources":{
  "includes":[
    {"pattern":"\\Qaws-lambda-runtime-interface-client.glibc.so\\E"}, 
    {"pattern":"\\Qaws-lambda-runtime-interface-client.musl.so\\E"}
  ]},
  "bundles":[]
}
```

Now, when that configuration added, when we run again in Lambda it finds the library and all the JNI calls are executed and we go to the rabbit hole of adding a lot of depedencies (tcnative, jetty alpn,...)

```
START RequestId: c3865327-7e0a-4ca1-bee5-fc06453f240e Version: $LATEST
Exception in thread "main" java.lang.Error: java.lang.NoClassDefFoundError: Lcom/amazonaws/services/lambda/runtime/api/client/runtimeapi/InvocationRequest;
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:195)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:188)
	at com.example.Foo.main(Foo.java:8)
Caused by: java.lang.NoClassDefFoundError: Lcom/amazonaws/services/lambda/runtime/api/client/runtimeapi/InvocationRequest;
	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:325)
	at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.NativeClient.next(NativeClient.java)
	at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.LambdaRuntimeClient.waitForNextInvocation(LambdaRuntimeClient.java:41)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:249)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:193)
	... 2 more
END RequestId: c3865327-7e0a-4ca1-bee5-fc06453f240e
REPORT RequestId: c3865327-7e0a-4ca1-bee5-fc06453f240e	Duration: 7.56 ms	Billed Duration: 410 ms	Memory Size: 512 MB	Max Memory Used: 104 MB	Init Duration: 401.83 ms	
RequestId: c3865327-7e0a-4ca1-bee5-fc06453f240e Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
