### ISSUE TITLE
Error building native image with rdsdata dependency

### ISSUE THREAD

**Issue by mrdanp** [micronaut-projects/micronaut-aws#1032]
I'm currently playing with micronaut, aws lambda and the Data API (aurora serverless). 
Packaging the application as a JAR and deploying to aws lambda works fine. But building a native image fails

### Task List

- [ x] Steps to reproduce provided
- [ x] Stacktrace (if present) provided
- [ x] Example that reproduces the problem uploaded to Github
- [ x] Full description of the issue provided (see below)

### Steps to Reproduce

1. See example application below
2. ./deploy.sh

### Expected Behaviour

Expected to have a native image.

### Actual Behaviour

Doesn't build. Here is the stacktrace.

```
Step 19/24 : RUN /usr/lib/graalvm/bin/native-image --no-server -cp build/libs/complete-*-all.jar
 ---> Running in 5de1698f06f6
[complete:24]    classlist:   7,680.39 ms,  0.96 GB
[complete:24]        (cap):     828.99 ms,  0.96 GB
[complete:24]        setup:   3,152.06 ms,  0.96 GB
Error: Error parsing resource configuration in jar:file:/home/application/build/libs/complete-0.1-all.jar!/META-INF/native-image/software.amazon.awssdk/sdk-core/resource-config.json:
Attribute 'resources' must be a list of resources
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ResourceConfigurationResources.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
The command '/bin/sh -c /usr/lib/graalvm/bin/native-image --no-server -cp build/libs/complete-*-all.jar' returned a non-zero code: 1
Unable to find image 'complete:latest' locally
docker: Error response from daemon: pull access denied for complete, repository does not exist or may require 'docker login': denied: requested 
access to the resource is denied.
```

Then I tried building again with -H:+ReportExceptionStackTraces
Here is the stacktrace

```
Error: Error parsing resource configuration in jar:file:/home/application/build/libs/complete-0.1-all.jar!/META-INF/native-image/software.amazon.awssdk/sdk-core/resource-config.json:
Attribute 'resources' must be a list of resources
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ResourceConfigurationResources.
com.oracle.svm.core.util.UserError$UserException: Error parsing resource configuration in jar:file:/home/application/build/libs/complete-0.1-all
.jar!/META-INF/native-image/software.amazon.awssdk/sdk-core/resource-config.json:
Attribute 'resources' must be a list of resources
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ResourceConfigurationResources.
at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:138)
at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:119)
at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:108)
at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:125)
at com.oracle.svm.hosted.ResourcesFeature.beforeAnalysis(ResourcesFeature.java:100)
at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:679)
at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:679)
at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
The command '/bin/sh -c /usr/lib/graalvm/bin/native-image --no-server -cp build/libs/complete-*-all.jar' returned a non-zero code: 1
```

### Environment Information

- **Micronaut Version:** 2.4.2
- **JDK Version:** 11

### Example Application

- used this as a starting point: https://github.com/micronaut-guides/mn-application-aws-lambda-graalvm/archive/master.zip (complete solution) found in the tutorials https://guides.micronaut.io/mn-application-aws-lambda-graalvm/guide/index.html
- bumped micronaut version to 2.4.2
- added this dependency implementation ("software.amazon.awssdk:rdsdata:2.16.41")
- added one controller to query the AWS DATA API

```
package example.micronaut;

import software.amazon.awssdk.services.rdsdata.RdsDataClient;
import software.amazon.awssdk.services.rdsdata.model.ExecuteStatementRequest;
import software.amazon.awssdk.services.rdsdata.model.ExecuteStatementResponse;
import software.amazon.awssdk.services.rdsdata.model.Field;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import java.util.List;

@Controller("/account")
public class AccountController {

    @Get
    public String index() {

        RdsDataClient rdsData = RdsDataClient.builder().build();
        ExecuteStatementRequest request = ExecuteStatementRequest.builder()
                .sql("SELECT * FROM Account")
                .resourceArn("arn:aws:xxxxx")
                .secretArn("arn:aws:secretsmanager:us-east-2:yyyyyyy")
                .database("serverlessdbname")
                .build();

        final ExecuteStatementResponse executeStatementResponse = rdsData.executeStatement(request);
        for (List<Field> fields: executeStatementResponse.records()) {
            long accountId = fields.get(0).longValue();
            String name = fields.get(1).stringValue();

            System.out.println(String.format("Fetched row: name = %s, id = %d", name, accountId));
        }
        return "success";
    }
}

```

**Comment by mrdanp** [comment]
It worked after I upgraded GRAALVM to 21.0.0.2. My apologies for trying that sooner.
