### ISSUE TITLE
 mn  aws-api-gateway-graal sample doesn't work 

### ISSUE THREAD

**Issue by Aleksandr-Filichkin** [micronaut-projects/micronaut-aws#108]
Hi,

I tried the sample for graalvm +aws lambda from https://micronaut-projects.github.io/micronaut-aws/latest/guide/#customRuntimes but it doesn't work

Micronaut Version: 1.2.5

I was able to build native image and deploy the Lambda to AWS.
 But test request  doesn't work
(aws lambda invoke --function-name my-app2 --payload '{"resource": "/{proxy+}", "path": "/ping", "httpMethod": "GET"}' build/response.txt)

CloudWatch Log is:

`WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.
START RequestId: 8f265328-1229-40eb-9842-06af2b5feb95 Version: $LATEST
com.amazonaws.serverless.exceptions.InvalidRequestEventException: Invalid Request: Illegal character in path at index 13: https://null/{proxy+}
at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:123)
at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:48)
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:204)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:131)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:77)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 13: https://null/{proxy+}
at java.net.URI.create(URI.java:852)
at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getUri(MicronautAwsProxyRequest.java:193)
at io.micronaut.http.HttpRequest.getPath(HttpRequest.java:85)
at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:79)
... 4 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 13: https://null/{proxy+}
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.checkChars(URI.java:3021)
at java.net.URI$Parser.parseHierarchical(URI.java:3105)
at java.net.URI$Parser.parse(URI.java:3053)
at java.net.URI.<init>(URI.java:588)
at java.net.URI.create(URI.java:850)
... 7 more
END RequestId: 8f265328-1229-40eb-9842-06af2b5feb95
REPORT RequestId: 8f265328-1229-40eb-9842-06af2b5feb95 Duration: 416.30 ms Billed Duration: 800 ms Memory Size: 128 MB Max Memory Used: 75 MB Init Duration: 339.96 ms
`

**Comment by graemerocher** [comment]
Please replace `/{proxy+}` with the actual path you are trying to invoke

**Comment by Aleksandr-Filichkin** [comment]
@graemerocher , but I'm trying to invoke "ping" path. 

For request should I send for this Lambda code?
`@Controller("/ping")
public class PingController {

	private Logger log = LoggerFactory.getLogger(PingController.class);

    @Get("/")
    public String ping() {
    	log.trace("Received a ping.");
    	return "{\"pong\":true}";
    }
}`

**Comment by graemerocher** [comment]
Seems a documentation error. Try:

```
aws lambda invoke --function-name my-app --payload '{"resource": "/ping", "path": "/ping", "httpMethod": "GET"}' build/response.txt
```

**Comment by Aleksandr-Filichkin** [comment]
Now it works. Thank you!
