### ISSUE TITLE
MicronautStreamHandler closes MongoClient after processing request which is undesirable

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#1187]
### Discussed in https://github.com/micronaut-projects/micronaut-aws/discussions/1177

<div type='discussions-op-text'>

<sup>Originally posted by **mayurtanna** September 11, 2021</sup>
Hi @sdelamo 

Like I mentioned in the issue https://github.com/micronaut-projects/micronaut-aws/issues/1077, when I use MicronautRequestStreamHandler, it seems to be destroying the MongoClient (so ultimately connectionpool) once processing the request and hence we get an exception like below for subsequent request.

So, what I believe is it might be due to StreamFunctionExecutor class's execute method which is getting called internally when we use MicronautRequestStreamHandler. In that method it is closing the applicationContext in finally clause which seem to be destroying MongoClient internally.

I would like to understand, is it desirable to close the applicationContext post handling the request ? Because in case of MicronautRequestHandler I didn't find like we are closing applicationContext post handling of the request. Also, what should I do to keep the connection open ? 

Can you provide your thoughts here ?

----------------Exception---------------
Connection pool shut down: java.lang.IllegalStateException
java.lang.IllegalStateException: Connection pool shut down
at org.apache.http.util.Asserts.check(Asserts.java:34)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at software.amazon.awssdk.http.apache.internal.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:8</div>

**Comment by sdelamo** [comment]
@mayurtanna I've created a PR that I think it fixes the issue.
