### ISSUE TITLE
Lambda Native Image with Deserialization Error

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#1376]
### Expected Behavior

AWS Lambda API Gateway Proxy Native Lambda to start

### Actual Behaviour

```
[main] INFO io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler - Starting Lambda Container Handler
[main] INFO io.micronaut.context.env.DefaultEnvironment - Established active environments: [ec2, cloud, lambda, function]
io.micronaut.http.client.exceptions.HttpClientResponseException: Error decoding HTTP response body: No bean introspection available for type [class com.amazonaws.serverless.proxy.model.AwsProxyRequest]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
```

### Steps To Reproduce

Dependencies:

```
    annotationProcessor("org.projectlombok:lombok")
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.micronaut.aws:micronaut-aws-sdk-v2")
    implementation("software.amazon.awssdk:s3") {
        exclude("software.amazon.awssdk", "apache-client")
        exclude("software.amazon.awssdk", "netty-nio-client")
    }
    implementation("software.amazon.awssdk:sso") {
        exclude("software.amazon.awssdk", "apache-client")
        exclude("software.amazon.awssdk", "netty-nio-client")
    }
    implementation("software.amazon.awssdk:url-connection-client")

    implementation("io.micronaut.reactor:micronaut-reactor")
    implementation("io.micronaut.reactor:micronaut-reactor-http-client")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut.tracing:micronaut-tracing-zipkin")
    implementation("jakarta.annotation:jakarta.annotation-api")

    implementation("io.micronaut.aws:micronaut-function-aws-api-proxy")

    compileOnly("org.projectlombok:lombok")

    runtimeOnly("org.slf4j:slf4j-simple")

    testImplementation("org.assertj:assertj-core")
    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation("org.testcontainers:localstack")
    testImplementation("org.testcontainers:testcontainers")

    compileOnly("org.graalvm.nativeimage:svm")

    implementation("io.micronaut:micronaut-validation")

    testImplementation("io.micronaut.aws:micronaut-function-aws-test")
    testImplementation("org.hamcrest:hamcrest")
    testImplementation("org.mockito:mockito-core")
```

SAM Lambda Declaration:

```
  LambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: "SomeFunctionName"
      VpcConfig:
         ...
      Environment:
        Variables:
           ....
      Handler: bootstrap
      Runtime: provided.al2

```

Makefile

```
build-LambdaFunction:
	$(GRADLE_CMD) buildNativeLambda
	unzip build/libs/function-0.1-lambda.zip -d $(ARTIFACTS_DIR)/
```

Using `sam build`

### Environment Information

- Operating System: MacOS
- GraalVM 22.0
- AWS Lambda `provided.al2` with `bootstrap` + `func`

### Version

Micronaut: 3.4.3

**Comment by driverpt** [comment]
`@TypeHint` missing for `com.amazonaws.serverless.proxy.model.AwsProxyRequest` ?

**Comment by sdelamo** [comment]
do you have a sample app?

**Comment by driverpt** [comment]
I'm creating it right now.

**Comment by driverpt** [comment]
@sdelamo , please check the Repo Here

https://github.com/driverpt/micronaut-aws-api-proxy-graalvm-error

Just tested it again:

```
START RequestId: 6044b2a5-1b2d-49f6-92b0-0ce5afc9e222 Version: $LATEST
11:35:31.036 [main] INFO  i.m.f.a.p.AbstractLambdaContainerHandler - Starting Lambda Container Handler
11:35:37.011 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [ec2, cloud, lambda, function]
io.micronaut.http.client.exceptions.HttpClientResponseException: Error decoding HTTP response body: No bean introspection available for type [class com.amazonaws.serverless.proxy.model.AwsProxyRequest]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
	at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2546)
	at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2389)
	at io.micronaut.http.client.netty.DefaultHttpClient$SimpleChannelInboundHandlerInstrumented.channelRead0(DefaultHttpClient.java:3145)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
```

Let me know if i can help or brainstorm the solution.

**Comment by driverpt** [comment]
cc @msailes

**Comment by driverpt** [comment]
Forgot to say, to Test, just invoke the Lambda with an example API Gateway V1 Payload in the UI. 

![image](https://user-images.githubusercontent.com/1164534/168550296-2713c5a9-1ccb-443a-b222-de4cd3751da6.png)

**Comment by driverpt** [comment]
Hey folks.

Any update on this?

**Comment by msailes** [comment]
Your SAM template has the handler as `bootstrap` I think it should be `io.micronaut.function.aws.proxy.MicronautLambdaHandler`

https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java

Has `@TypeHint` for `com.amazonaws.serverless.proxy.model.AwsProxyRequest`

**Comment by driverpt** [comment]
Hello @msailes ,

Having the same result:

![image](https://user-images.githubusercontent.com/1164534/169477811-2366f3e5-143a-452d-b4a9-47e4768b848d.png)
![image](https://user-images.githubusercontent.com/1164534/169477899-753d97e2-3e52-488d-951f-1fe14e1247fb.png)

**Comment by sdelamo** [comment]
I've not had the time yet to check your code. 

You should not need to do this but you can generate `@Introspected` metadata information about a class. 

https://micronaut-projects.github.io/micronaut-core/latest/guide/#introspection: 

> If the class to introspect is already compiled and not under your control, an alternative option is to define a > configuration class with the classes member of the [@Introspected](https://micronaut-projects.github.io/micronaut-core/latest/api/io/micronaut/core/annotation/Introspected.html) annotation set.

You could add  `@Introspected(class = com.amazonaws.serverless.proxy.model.AwsProxyRequest)` to one of your classes. 

Let me know if it works. 

I hope to be able to check your example soon.

**Comment by driverpt** [comment]
Hello @sdelamo , thanks for the reply.

I'm still having the same issue with the recommended change

**Comment by driverpt** [comment]
Updated Micronaut to 3.5.0 and added the following annotations:

```
@Introspected(classes = com.amazonaws.serverless.proxy.model.AwsProxyRequest.class)
@SerdeImport(AwsProxyRequest.class)
```

Now i'm getting a different error:

```
Request loop failed with: Error decoding HTTP response body: No bean introspection available for type [class com.amazonaws.serverless.proxy.model.AwsProxyRequestContext]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
```

I also noticed that a PR already has the necessary code to get this to work:

https://github.com/micronaut-projects/micronaut-aws/pull/1323/files#diff-dd8cf116b1d2f8e327fcac6c6f62b5464b6d52d16c6a8563be369b7c6fdea1a1R120-R131

Do we have an ETA for this PR to be merged?

Thanks
