### ISSUE TITLE
"Illegal base64 character" Exception of DefaultServletToAwsProxyResponseAdapter if HttpResponse<ByteArray> is returned

### ISSUE THREAD

**Issue by Onvistlex** [micronaut-projects/micronaut-aws#1545]
### Expected Behavior

A `@Get` function of a Kotlin Controller should be able to return a `HttpRespone<ByteArray>` without exception

### Actual Behaviour

If a `@Get` function of a Kotlin Controller returns a `HttpRespone<ByteArray>`  an `IllegalArgumentException: Illegal base64 character d` is thrown

### Steps To Reproduce

1. create a micronaut application with following settings with https://micronaut.io/launch 
![image](https://user-images.githubusercontent.com/93600641/209436292-6f74fb7f-0bdd-4935-bc15-72837225002e.png)
or clone: https://github.com/Ic-ks/micronaut-aws-bas64-bug 
2. if not cloned, replace `fun index() = mapOf("message" to "Hello World")` with `fun index() = HttpResponse.ok(ByteArray(256) { it.toByte() }).contentType(MediaType.APPLICATION_OCTET_STREAM_TYPE)`
3. execute gradle application `run` task (`./gradlew app:run`)
4. open  http://localhost:8080
5. exception is thrown:
```
java.lang.IllegalArgumentException: Illegal base64 character d
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
        at io.micronaut.function.aws.proxy.test.DefaultServletToAwsProxyResponseAdapter.parseBodyAsBytes(DefaultServletToAwsProxyResponseAdapter.java:77)
        at io.micronaut.function.aws.proxy.test.DefaultServletToAwsProxyResponseAdapter.handle(DefaultServletToAwsProxyResponseAdapter.java:55)
        at io.micronaut.function.aws.proxy.test.AwsApiProxyTestServer$AwsProxyHandler.handle(AwsApiProxyTestServer.java:210)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

After debugging the micronaut code I discovered a possible cause:
`MicronautAwsProxyResponse.encodeBody()` uses `Base64.getMimeEncoder().encodeToString(encoded)` to serialize the response and `DefaultServletToAwsProxyResponseAdapter.parseBodyAsBytes()` uses `Base64.getDecoder().decode(body)` to deserialize the response. 
If `DefaultServletToAwsProxyResponseAdapter.parseBodyAsBytes()` would use `Base64.getMimeDecoder().decode()` this error would probably be fixed. 

### Environment Information

Ubuntu 20.04

### Example Application

https://github.com/Ic-ks/micronaut-aws-bas64-bug

### Version

3.7.5

**Comment by timyates** [comment]
@Onvistlex Thank you so much for raising this, and more-so for the excellent diagnosis and reproducer 👍

**Comment by Paramounttinder** [comment]
> [@Onvistlex](https://github.com/Onvistlex) Thank you so much for raising this, and more-so for the excellent diagnosis and reproducer 👍





https://lnkr.fun/f77be63
