### ISSUE TITLE
Unable to inject com.amazonaws.services.lambda.runtime.Context into Serverless Function

### ISSUE THREAD

**Issue by gridview** [micronaut-projects/micronaut-aws#1615]
### Expected Behavior

Be able to access context from AWS Lambda handler in micronaut. 

I have this simple handler just to see if context can be injected and it is not working.

```java
package com.example;

import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.context.BeanProvider;
import io.micronaut.context.annotation.Any;
import io.micronaut.function.aws.MicronautRequestHandler;
import jakarta.inject.Inject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collections;

public class FunctionRequestHandler extends MicronautRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
    private final Logger logger = LoggerFactory.getLogger(FunctionRequestHandler.class);
    @Inject
    ObjectMapper objectMapper;

    @Any
    BeanProvider<com.amazonaws.services.lambda.runtime.Context> context;

    @Override
    public APIGatewayProxyResponseEvent execute(APIGatewayProxyRequestEvent input) {
        APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
        logger.info("Fname:{}-{}", context.get().getFunctionName(), context.get().getFunctionVersion());
        try {
            String json = objectMapper.writeValueAsString(Collections.singletonMap("message", "Hello World"));
            response.setStatusCode(200);
            response.setBody(json);
        } catch (JsonProcessingException e) {
            response.setStatusCode(500);
        }
        return response;
    }
}
```

### Actual Behaviour

Logs from CloudWatch, Log trace is enabled

```
15:17:00.882 [main] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: com.example.FunctionRequestHandler] for instance: com.example.FunctionRequestHandler@77f1baf5
15:17:00.883 [main] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: objectMapper
15:17:00.883 [main] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: @Any context
15:17:00.883 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: BeanProvider context
15:17:00.883 [main] DEBUG i.m.context.DefaultBeanContext -   interface io.micronaut.context.BeanProvider null io.micronaut.inject.provider.BeanProviderDefinition@e01aab8
15:17:00.883 [main] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@e01aab8]
15:17:00.883 [main] DEBUG i.m.context.DefaultBeanContext -   interface io.micronaut.context.BeanProvider null io.micronaut.inject.provider.BeanProviderDefinition@e01aab8
15:17:00.883 [main] DEBUG i.m.context.DefaultBeanContext - Qualifying bean [context] for qualifier: @Any 
15:17:00.883 [main] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@e01aab8] for type: @Any context 
15:17:00.883 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: Context T
15:17:00.884 [main] DEBUG i.m.context.DefaultBeanContext - No bean candidates found for type: Context T
15:17:00.884 [main] DEBUG io.micronaut.context.lifecycle - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@6c40365c] from definition [io.micronaut.inject.provider.BeanProviderDefinition@e01aab8] with qualifier [@Any]
START RequestId: 64cd08aa-0ee2-485e-961d-f89867627dd8 Version: $LATEST
15:17:00.969 [main] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: T
15:17:00.969 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: Context T
15:17:00.970 [main] DEBUG i.m.context.DefaultBeanContext - No bean candidates found for type: Context T
No bean of type [com.amazonaws.services.lambda.runtime.Context] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).: io.micronaut.context.exceptions.NoSuchBeanException
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [com.amazonaws.services.lambda.runtime.Context] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2805)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
	at io.micronaut.inject.provider.BeanProviderDefinition$1.get(BeanProviderDefinition.java:81)
	at com.example.FunctionRequestHandler.execute(FunctionRequestHandler.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

### Steps To Reproduce

1. Build Lambda with ShadowJar in IntelliJ
2. Upload to a lambda function in AWS
3. Test the Lambda with default request.
4. Read the logs

### Environment Information

- Operating System: AWS Lambda
- JDK 11 correcto

### Example Application

https://github.com/gridview/test_lambda_context.git

### Version

3.8.4

**Comment by sdelamo** [comment]
@gridview have you tried https://micronaut-projects.github.io/micronaut-aws/latest/guide/#lambdacontext?

**Comment by gridview** [comment]
> @gridview have you injecting in a bean not in the handler?
> 
> https://micronaut-projects.github.io/micronaut-aws/latest/guide/#lambdacontext?

Injected in both a test service (bean) as well as the handler with no success.

**Comment by sdelamo** [comment]
I change your class to: 

```
package com.example;

import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.context.BeanProvider;
import io.micronaut.context.annotation.Any;
import io.micronaut.function.aws.MicronautRequestHandler;
import jakarta.inject.Inject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collections;

public class FunctionRequestHandler extends MicronautRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
    private final Logger logger = LoggerFactory.getLogger(FunctionRequestHandler.class);
    @Inject
    ObjectMapper objectMapper;

    @Any
    public BeanProvider<Context> context;

    @Override
    public APIGatewayProxyResponseEvent execute(APIGatewayProxyRequestEvent input) {
        APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
        logger.info("Fname:{}-{}", getContext().getFunctionName(), getContext().getFunctionVersion());
        try {
            String json = objectMapper.writeValueAsString(Collections.singletonMap("message", "Hello World"));
            response.setStatusCode(200);
            response.setBody(json);
        } catch (JsonProcessingException e) {
            response.setStatusCode(500);
        }
        return response;
    }

    Context getContext() {
        return context.get();
    }
}
```

and the test to: 

```
package com.example;

import com.amazonaws.services.lambda.runtime.ClientContext;
import com.amazonaws.services.lambda.runtime.CognitoIdentity;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class FunctionRequestHandlerTest {

    private static FunctionRequestHandler handler;

    @BeforeAll
    public static void setupServer() {
        handler = new FunctionRequestHandler();
    }

    @AfterAll
    public static void stopServer() {
        if (handler != null) {
            handler.getApplicationContext().close();
        }
    }

    @Test
    public void testHandler() {
        APIGatewayProxyRequestEvent request = new APIGatewayProxyRequestEvent();
        request.setHttpMethod("GET");
        request.setPath("/");
        APIGatewayProxyResponseEvent response = handler.handleRequest(request, new Context() {
            @Override
            public String getAwsRequestId() {
                return null;
            }

            @Override
            public String getLogGroupName() {
                return null;
            }

            @Override
            public String getLogStreamName() {
                return null;
            }

            @Override
            public String getFunctionName() {
                return "foo";
            }

            @Override
            public String getFunctionVersion() {
                return "0.1";
            }

            @Override
            public String getInvokedFunctionArn() {
                return null;
            }

            @Override
            public CognitoIdentity getIdentity() {
                return null;
            }

            @Override
            public ClientContext getClientContext() {
                return null;
            }

            @Override
            public int getRemainingTimeInMillis() {
                return 0;
            }

            @Override
            public int getMemoryLimitInMB() {
                return 0;
            }

            @Override
            public LambdaLogger getLogger() {
                return null;
            }
        });
        assertEquals(200, response.getStatusCode().intValue());
        assertEquals("{\"message\":\"Hello World\"}", response.getBody());
    }
}
````

and the context is injected in the handler. At least in the test.

**Comment by sdelamo** [comment]
I deployed to Lambda send a tes event and the injection seems fine: 

```
Picked up JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
13:26:04.596 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [ec2, cloud, function, lambda]
START RequestId: 61252ccf-abc6-4a47-b819-5dbfffe8e9a9 Version: $LATEST
13:26:05.595 [main] INFO  **com.example.FunctionRequestHandler - Fname:MnHelloWorldStack-helloworldjavafunctionD685C1BE-iP06SdgpMANz-$LATEST**
END RequestId: 61252ccf-abc6-4a47-b819-5dbfffe8e9a9
REPORT RequestId: 61252ccf-abc6-4a47-b819-5dbfffe8e9a9	Duration: 57.67 ms	Billed Duration: 58 ms	Memory Size: 2024 MB	Max Memory Used: 138 MB	Init Duration: 2217.56 ms	
```
