### ISSUE TITLE
NullPointerException in MicronautLambdaAuthenticationFetcher.fetchAuthentication

### ISSUE THREAD

**Issue by asantare** [micronaut-projects/micronaut-aws#1826]
### Expected Behavior

NPE should not occur if the AWS API Gateway doesn't have an Authorizer defined

### Actual Behaviour

The following NPE occurs

```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: null
java.lang.NullPointerException: null
  at io.micronaut.function.aws.proxy.security.MicronautLambdaAuthenticationFetcher.fetchAuthentication(MicronautLambdaAuthenticationFetcher.java:82)
  at io.micronaut.function.aws.proxy.security.MicronautLambdaAuthenticationFetcher.fetchAuthentication(MicronautLambdaAuthenticationFetcher.java:58)
  at io.micronaut.function.aws.proxy.security.MicronautLambdaAuthenticationFetcher.fetchAuthentication(MicronautLambdaAuthenticationFetcher.java:42)
  at io.micronaut.security.filters.SecurityFilter.lambda$doFilter$0(SecurityFilter.java:110)
  at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)
  at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:335)
  at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
  at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
  at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
  at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
  at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
  at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl.onComplete(ReactorExecutionFlowImpl.java:89)
  at io.micronaut.servlet.http.ServletHttpHandler.service(ServletHttpHandler.java:223)
  at io.micronaut.servlet.http.ServletHttpHandler.exchange(ServletHttpHandler.java:176)
  at io.micronaut.servlet.http.ServletHttpHandler.exchange(ServletHttpHandler.java:166)
  at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction.handleRequest(ApiGatewayProxyRequestEventFunction.java:56)
  at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction.handleRequest(ApiGatewayProxyRequestEventFunction.java:30)
  at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:406)
  at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:164)
  at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:41)
```

### Steps To Reproduce

1. define a AWS lambda with a bean implementing the `io.micronaut.security.authentication.AuthenticationProvider`
2. define an API Gateway without an authorizer to invoke the Lambda via proxy
3. invoke the lambda with the 'Authorization' header in the request

### Environment Information

- AWS lambda provided runtime (it should be the case also with java17)
- JDK 17
- 

### Version

4.0.2-SNAPSHOT

**Comment by asantare** [comment]
the same code used to work in Micronaut 3.9.4
