### ISSUE TITLE
NPE in handler

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-aws#1864]
### Issue description

```
Cannot invoke "String.length()" because "this.input" is null: java.lang.NullPointerException
java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at java.base/java.net.URI.create(Unknown Source)
	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyServletRequest.<init>(ApiGatewayProxyServletRequest.java:59)
	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyEventHandler.createExchange(ApiGatewayProxyEventHandler.java:55)
	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyEventHandler.createExchange(ApiGatewayProxyEventHandler.java:35)
	at io.micronaut.servlet.http.ServletHttpHandler.exchange(ServletHttpHandler.java:165)
	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction.handleRequest(ApiGatewayProxyRequestEventFunction.java:56)
	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction.handleRequest(ApiGatewayProxyRequestEventFunction.java:30)

```

**Comment by sdelamo** [comment]
I got this in AWS Lambda console 👆🏻
