### ISSUE TITLE
Jackson Annotations not serializing JSON

### ISSUE THREAD

**Issue by JulianVKelly** [micronaut-projects/micronaut-aws#207]
I'm in the process of following this guide - and so far so good : https://guides.micronaut.io/micronaut-function-graalvm-aws-lambda-gateway/guide/index.html

On thing I'm trying to do is annotate my kotlin data classes with `@JsonProperty("foo")` annotations to customize how they're serialized but this doesn't seem to work. Unless I use `@Introspected` my classes will either be serialized as blank of I'll receive an exception.

My controller and data class:

```
data class HealthCheckResponse(val message: String)

@Controller("/")
class MyController {

    @Get("/health")
    fun health() = HealthCheckResponse("ok")
}
```

**Examples**

1. Running curl with no annotations (as above)

Expected
```
{"message" : "ok"}
```
Actual
```
com.amazonaws.serverless.exceptions.InvalidResponseObjectException: Invalid Response: Error encoding object [HealthCheckResponse(message=this should say test)] to JSON: No serializer found for class com.foo.bar.controller.HealthCheckResponse and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at io.micronaut.function.aws.proxy.MicronautAwsProxyResponse.encodeInternal(MicronautAwsProxyResponse.java:186)
	at io.micronaut.function.aws.proxy.MicronautAwsProxyResponse.encodeBody(MicronautAwsProxyResponse.java:156)
	at io.micronaut.function.aws.proxy.MicronautResponseWriter.writeResponse(MicronautResponseWriter.java:100)
	at io.micronaut.function.aws.proxy.MicronautResponseWriter.writeResponse(MicronautResponseWriter.java:50)
	at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:215)
	at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:131)
	at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:77)
Caused by: io.micronaut.http.codec.CodecException: Error encoding object [HealthCheckResponse(message=this should say test)] to JSON: No serializer found for class com.foo.bar.controller.HealthCheckResponse and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:215)
	at io.micronaut.function.aws.proxy.MicronautAwsProxyResponse.encodeInternal(MicronautAwsProxyResponse.java:182)
	... 6 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.foo.bar.controller.HealthCheckResponse and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:404)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3428)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:212)
	... 7 more
```

2. Annotate with JsonInclude
```
@JsonInclude(JsonInclude.Include.NON_NULL)
data class HealthCheckREsponse(val message: String)
```

Exptected
```
{"message" : "ok"}
```

Actual
```
{}
```

3. Annotate class with introspected and JsonProperty
```
@Introspected
data class HealthCheckResponse(@JsonProperty("foo")val message: String)
```

Expected
```
{"foo" : "ok"}
```

Actual
```
{"message" : "ok"}
```

Only interesting thing to note is that in example 2, even though it returns a blank response, it doesn't error like in example 1 so it is recognizing there are parsers!

**Comment by adamkobor** [comment]
I have the same issue (see example no. 3) with `@JsonProperty` annotations in native images

**Comment by ilopmar** [comment]
`@Introspected` is kind of mandatory. Jackson uses reflection so unless you tell those classes to GraalVM it won't work. When annotating a POJO with `@Introspected` Micronaut will generate [Bean Introspection Metadata](https://docs.micronaut.io/latest/guide/index.html#introspection). Then the Jackson module we have for serialization/deserialization will use it. So, even if you don't use GraalVM, my recommendation is always annotate your POJOs with `@Introspected` because you will benefit from serialization/deserializing POJOs from/to json without using reflection. For running on the JVM this is not mandatory, but for GraalVM it is.

Having said that, what I would try is to recreate the same example with Java instead with Kotlin because we have applications and tests and `@JsonProperty` should work.

**Comment by msandy10** [comment]
Hi Team, I have recently upgraded Micronauts from 1.1.1 to 1.3.6 and AWS SDK Lambda 2 with GraalVM Native image, we are invoking lambda function using request_response type and capturing in below model ResponsePayload, Getting similar issue as shown in below message


- **Micronauts** : 1.3.5
- **Micronaut Data** : 1.10
- **AWS SDK Lambda** : 2.12.0
- **GraalVM** : 19.2.1

`timestamp,message
1599200500117,"START RequestId: 985f630f-4f67-4c03-981d-d260dab8b58e Version: $LATEST
"
"
1599200502197,"com.amazonaws.serverless.exceptions.InvalidResponseObjectException: Invalid Response: Error encoding object [Invalid JSON: Cannot construct instance of `com.trimble.engage.connector.ResponsePayload` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
"
1599200502197,"at [Source: (String)""{""statusCode"":404,""multiValueHeaders"":{},""isBase64Encoded"":false}""; line: 1, column: 2]] to JSON: No serializer found for class java.util.Optional and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.micronaut.http.hateoas.JsonError[""logref""])
"
1599200502197,"at io.micronaut.function.aws.proxy.MicronautAwsProxyResponse.encodeInternal(MicronautAwsProxyResponse.java:186)
"
1599200502197,"at io.micronaut.function.aws.proxy.MicronautAwsProxyResponse.encodeBody(MicronautAwsProxyResponse.java:156)
"
1599200502197,"at io.micronaut.function.aws.proxy.MicronautResponseWriter.writeResponse(MicronautResponseWriter.java:100)
"
1599200502197,"at io.micronaut.function.aws.proxy.MicronautResponseWriter.writeResponse(MicronautResponseWriter.java:50)
"
1599200502197,"at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:215)
"
1599200502197,"at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:131)
"
1599200502197,"at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:77)
"
1599200502197,"Caused by: io.micronaut.http.codec.CodecException: Error encoding object [Invalid JSON: Cannot construct instance of `com.trimble.engage.connector.ResponsePayload` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
"
1599200502197,"at [Source: (String)""{""statusCode"":404,""multiValueHeaders"":{},""isBase64Encoded"":false}""; line: 1, column: 2]] to JSON: No serializer found for class java.util.Optional and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.micronaut.http.hateoas.JsonError[""logref""])
"
1599200502197,"at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:215)
"
1599200502197,"at io.micronaut.function.aws.proxy.MicronautAwsProxyResponse.encodeInternal(MicronautAwsProxyResponse.java:182)
"
1599200502197,"... 6 more
"
1599200502197,"Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class java.util.Optional and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.micronaut.http.hateoas.JsonError[""logref""])
"
1599200502197,"at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
"
1599200502197,"at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:404)
"
1599200502198,"at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
"
1599200502198,"at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
"
1599200502198,"at io.micronaut.jackson.modules.BeanIntrospectionModule$BeanIntrospectionPropertyWriter.serializeAsField(BeanIntrospectionModule.java:660)
"
1599200502198,"at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
"
1599200502198,"at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
"
1599200502198,"at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
"
1599200502198,"at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
"
1599200502198,"at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4110)
"
1599200502198,"at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3437)
"
1599200502198,"at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:212)
"
1599200502198,"... 7 more
"
1599200502206,"END RequestId: 985f630f-4f67-4c03-981d-d260dab8b58e
"
1599200502206,"REPORT RequestId: 985f630f-4f67-4c03-981d-d260dab8b58e	Duration: 1571.69 ms	Billed Duration: 2300 ms	Memory Size: 2944 MB	Max Memory Used: 139 MB	Init Duration: 707.78 ms	
"`

`
InvokeRequest invokeRequest = InvokeRequest.builder()
                .functionName(entitlementFunction)
                .invocationType(InvocationType.REQUEST_RESPONSE)
                .payload(payload)
                .build();
		InvokeResponse response = lambdaClient.invoke(invokeRequest);
		String responsePayload = response.payload().asUtf8String() ;
    	ResponsePayload responseBody = mapper.readValue(responsePayload, ResponsePayload.class);
    	return responseBody.getBody();
`
`
@Introspected
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({ "multiValueHeaders", "body", "statusCode", "isBase64Encoded" })
public class ResponsePayload {

	@JsonProperty("multiValueHeaders")
	private MultiValueHeaders multiValueHeaders;
	@JsonProperty("body")
	private String body;
	@JsonProperty("statusCode")
	private Integer statusCode;
	@JsonProperty("isBase64Encoded")
	private Boolean isBase64Encoded;
	@JsonIgnore
	private Map<String, Object> additionalProperties = new HashMap<String, Object>();

	public ResponsePayload() {
		super();
	}

	public ResponsePayload(MultiValueHeaders multiValueHeaders, String body, Integer statusCode,
			Boolean isBase64Encoded, Map<String, Object> additionalProperties) {
		super();
		this.multiValueHeaders = multiValueHeaders;
		this.body = body;
		this.statusCode = statusCode;
		this.isBase64Encoded = isBase64Encoded;
		this.additionalProperties = additionalProperties;
	}


	@JsonProperty("multiValueHeaders")
	public MultiValueHeaders getMultiValueHeaders() {
		return multiValueHeaders;
	}

	@JsonProperty("multiValueHeaders")
	public void setMultiValueHeaders(MultiValueHeaders multiValueHeaders) {
		this.multiValueHeaders = multiValueHeaders;
	}

	@JsonProperty("body")
	public String getBody() {
		return body;
	}

	@JsonProperty("body")
	public void setBody(String body) {
		this.body = body;
	}

	@JsonProperty("statusCode")
	public Integer getStatusCode() {
		return statusCode;
	}

	@JsonProperty("statusCode")
	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	@JsonProperty("isBase64Encoded")
	public Boolean getIsBase64Encoded() {
		return isBase64Encoded;
	}

	@JsonProperty("isBase64Encoded")
	public void setIsBase64Encoded(Boolean isBase64Encoded) {
		this.isBase64Encoded = isBase64Encoded;
	}

	@JsonAnyGetter
	public Map<String, Object> getAdditionalProperties() {
		return this.additionalProperties;
	}

	@JsonAnySetter
	public void setAdditionalProperty(String name, Object value) {
		this.additionalProperties.put(name, value);
	}
}
`
can you please assist me to resolve the above issue

**Comment by kastork** [comment]
My problem appears to be related.

When using SAM cli, the lambda request fails because mn is returning `'base64Encoded':False` instead of `'isBase64Encoded':False`

This is true even after adding

`    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.0")` to the build

My test is the "launch" generated example, but I subclassed `MicronautLambdaHandler` to add some log output.
```
2020-09-26 14:12:29 127.0.0.1 - - [26/Sep/2020 14:12:29] "POST /book HTTP/1.1" 502 -
Invoking com.example.ProxyHandler (java11)
Decompressing /Users/kirk/s/local/cdk-mn/backend/build/libs/demo-all.jar
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-java11:rapid-1.3.2.

Mounting /private/var/folders/66/_95_86950lb9drnn0s2dp5h40000gn/T/tmp7u_dy22e as /var/task:ro,delegated inside runtime container
21:22:21.774 [main] INFO  i.m.f.a.p.AbstractLambdaContainerHandler - Starting Lambda Container Handler
21:22:21.957 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [ec2, cloud, function, lambda]
21:22:25.337 [main] DEBUG com.example.ProxyHandler - My handler bean is here.
START RequestId: be698e45-dbd2-12fe-2505-11dadf8c586f Version: $LATEST
21:22:25.418 [main] DEBUG com.example.ProxyHandler - POST
21:22:25.418 [main] DEBUG com.example.ProxyHandler - /book
21:22:25.418 [main] DEBUG com.example.ProxyHandler - { "name":  "foo"}
21:22:25.418 [main] DEBUG com.example.ProxyHandler - lambdainternal.api.LambdaContext@47eaca72
21:22:27.689 [main] DEBUG com.example.BookController - Request body is Book(name=foo)
21:22:27.789 [main] DEBUG com.example.ProxyHandler - Actual AwsProxyResponse is of type com.amazonaws.serverless.proxy.model.AwsProxyResponse
END RequestId: be698e45-dbd2-12fe-2505-11dadf8c586f
REPORT RequestId: be698e45-dbd2-12fe-2505-11dadf8c586f  Init Duration: 4482.57 ms       Duration: 2383.99 ms    Billed Duration: 2400 ms        Memory Size: 512 MB     Max Memory Used: 109 MB   
Invalid lambda response received: Invalid API Gateway Response Keys: {'base64Encoded'} in {'statusCode': 200, 'multiValueHeaders': {'Content-Type': ['application/json']}, 'body': '{"name":"foo","isbn":"8c81911c-09e2-48ef-a11d-5eec1d8af592"}', 'base64Encoded': False}
2020-09-26 14:22:29 127.0.0.1 - - [26/Sep/2020 14:22:29] "POST /book HTTP/1.1" 502 -
```

I do see that the type `AwsProxyResponse` does specify the JsonProperty name, which _should_ do it.

```
    @JsonProperty("isBase64Encoded")
    public boolean isBase64Encoded() {
        return isBase64Encoded;
    }

    public void setBase64Encoded(boolean base64Encoded) {
        isBase64Encoded = base64Encoded;
    }

```

**Comment by graemerocher** [comment]
@kastork please upload an example with steps to reproduce

**Comment by kastork** [comment]
Since this seems to be more than just a Jackson serialization issue, I've made a separate issue #544 that has a reproducer project attached.

**Comment by adamkobor** [comment]
I had a similar issue, regardless AWS: I've added a `@field:JsonProperty("some_value")` annotation to a property of a Kotlin data class, let's call it `ResponseData` for the sake of example. Then I've used it in a declarative client as a return type of `Single<ResponseData>`, but Jackson was unable to deserialize the JSON response with a `some_value` property in it into a `ResponseData` object.

```kotlin
@Introspected
data class ResponseData(
  @field:JsonProperty("some_value")
  val someValue: String
)
```

However, this approach works perfectly when I try to use a data class like this as a request body:

```kotlin
@Introspected
data class RequestData(
  @field:JsonProperty("some_value")
  val someValue: String
)

@Post("/some-path")
fun postSomething(@Body requestData: RequestData): Single<String>
```

In this case `RequestData` will be deserialized to a JSON like this:

```json
{
  "some_value": "value"
}
```

I've also tried to use `@JsonAlias` with no luck.

**Comment by turbolaban** [comment]
Apparently `@JsonProperty` works for deserializing and `@field:JsonProperty` works for serializing. So this will give the correct behaviour in both cases:
```
@Introspected
data class SomeData(
  @JsonProperty("some_value")
  @field:JsonProperty("some_value")
  val someValue: String
)
```

**Comment by abondar24** [comment]
Question regarding the following situation: what if this exception happens on pojo from externlal library?
