### ISSUE TITLE
InvalidRequestEventException

### ISSUE THREAD

**Issue by mguajardo** [micronaut-projects/micronaut-aws#274]
Hi, 
Im getting the following error:

> com.amazonaws.serverless.exceptions.InvalidRequestEventException: Invalid Request: Cannot create TypeBindings for class [Ljava.lang.Double; with 1 type parameter: class expects 0

If I run it on a server it works fine.

My code looks like this

`@Put("/clientes/{clienteId}/ubicacion")`
     `public ResultadoWS saveUbicacionCliente(int clienteId,@Body Double[] ubicacion, @NotNull Authentication authentication){ ... }`
`

Full stacktrace:
com.amazonaws.serverless.exceptions.InvalidRequestEventException: Invalid Request: Cannot create TypeBindings for class [Ljava.lang.Double; with 1 type parameter: class expects 0
at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:123)
at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:48)
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:204)
at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxyStream(AbstractLambdaContainerHandler.java:239)
at com.oss.facturable.movil.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:27)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:897)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:228)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:162)
at lambdainternal.AWSLambda.main(AWSLambda.java:157)
Caused by: java.lang.IllegalArgumentException: Cannot create TypeBindings for class [Ljava.lang.Double; with 1 type parameter: class expects 0
at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:126)
at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:96)
at com.fasterxml.jackson.databind.type.TypeFactory.constructParametricType(TypeFactory.java:1005)
at io.micronaut.jackson.JacksonConfiguration.constructType(JacksonConfiguration.java:341)
at io.micronaut.jackson.codec.JacksonMediaTypeCodec.constructJavaType(JacksonMediaTypeCodec.java:227)
at io.micronaut.jackson.codec.JacksonMediaTypeCodec.decode(JacksonMediaTypeCodec.java:187)
at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:108)
... 8 more

**Comment by chkpnt** [comment]
I can confirm having the same issue when having a `@Valid`-annotated bean which contains an enum, where the to be validated json-representations contains an invalid enum value.

Jackson is throwing an `InvalidFormatException`, leading to a `CodecException` which is then catched by `MicronautRequestReader` and rethrown as an `InvalidRequestEventException`.

```
07:15:14.078 [main] ERROR i.m.f.a.p.AbstractLambdaContainerHandler - Error while handling request
com.amazonaws.serverless.exceptions.InvalidRequestEventException: Invalid Request: Error decoding JSON stream for type [request]: Cannot deserialize value of type `[...].SubscriptionRequest$Salutation` from String "MRasdf": not one of the values accepted for Enum class: [MR, MRS, NOT_SELECTED]
 at [Source: (String)"[...]"; line: 1, column: 90] (through reference chain: [...].SubscriptionRequest["salutation"])
	at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:123)
	at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:48)
	at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:204)
	at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxyStream(AbstractLambdaContainerHandler.java:239)
	at de.kkeu.webshop.newsletter.Application.handleRequest(Application.java:37)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:258)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192)
	at lambdainternal.AWSLambda.main(AWSLambda.java:187)
Caused by: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [request]: Cannot deserialize value of type `[...].SubscriptionRequest$Salutation` from String "MRasdf": not one of the values accepted for Enum class: [MR, MRS, NOT_SELECTED]
Caused by: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [request]: Cannot deserialize value of type `[...]SubscriptionRequest$Salutation` from String "MRasdf": not one of the values accepted for Enum class: [MR, MRS, NOT_SELECTED]

 at [Source: (String)"[...]"; line: 1, column: 90] (through reference chain: [...].SubscriptionRequest["salutation"])
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.decode(JacksonMediaTypeCodec.java:193)
	at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:108)
	... 8 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `[...].SubscriptionRequest$Salutation` from String "MRasdf": not one of the values accepted for Enum class: [MR, MRS, NOT_SELECTED]
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `[...].SubscriptionRequest$Salutation` from String "MRasdf": not one of the values accepted for Enum class: [MR, MRS, NOT_SELECTED]

 at [Source: (String)"[...]"; line: 1, column: 90] (through reference chain: [...])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1679)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:935)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at io.micronaut.jackson.modules.BeanIntrospectionModule$BeanIntrospectionSetter.deserializeAndSet(BeanIntrospectionModule.java:741)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3182)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.decode(JacksonMediaTypeCodec.java:190)
```

I have a custom `ExceptionHandler` in my codebase, which isn't called by Micronout in this case.

This issue doesn't occur if the bean validation fails due to a failing constraint.

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by ktholen** [comment]
I am not sure if this is the same issue, but we are getting an issue where a 500 internal server error is always returned when the request cant be deserialized. We are using `MicronautLambdaContainerHandler` and that handler uses a `new MicronautAwsProxyExceptionHandler(lambdaContainerEnvironment)` set within its constructor. It looks like since the reader is throwing the exception in the `proxy` function in `AbstractLambdaContainerHandler` prior to the `handleRequest` method the ExceptionHandlers are not called and instead the default `MicronautAwsProxyExceptionHandler` is called instead.

If you think this is a separate issue I will create a new issue. Working on pushing up an example project.

**Comment by chkpnt** [comment]
I've just uploaded an demonstrator at https://github.com/chkpnt/micronaut-aws-issue-274

You can use swagger-ui to send the requests:
1. `./gradlew run` -> http://localhost:8080/swagger/views/swagger-ui/index.html
1. `./sam-local.sh` -> http://localhost:3000/swagger/views/swagger-ui/index.html

In the first case, where `MicronautLambdaRuntime` isn't used, I get the following response (HTTP 400) for an invalid enum value:

<img width="1188" alt="grafik" src="https://user-images.githubusercontent.com/1956979/86540986-56cb5b00-bf09-11ea-8247-f8818c0bf585.png">

In the second case, an HTTP 500 is returned:

<img width="1200" alt="grafik" src="https://user-images.githubusercontent.com/1956979/86541079-41a2fc00-bf0a-11ea-950c-a7bc36c95e7a.png">

The normal bean validation on the `emailAddress`- and `name`-field works in both cases.

**Comment by chkpnt** [comment]
Any update here?

**Comment by alvarosanchez** [comment]
Duplicates #52.

I noticed in the example application that the micronaut-aws version used was 1.3.9. This has changed in micronaut-aws 2.x.

Since #306, you can register a custom codec exception handler like:

```java
@Singleton
public class CodecExceptionExceptionHandler implements ExceptionHandler<CodecException, HttpResponse<String>> {

    @Override
    public HttpResponse<String> handle(HttpRequest request, CodecException exception) {
        return HttpResponse.badRequest("Invalid JSON: " + exception.getMessage()).contentType(MediaType.APPLICATION_JSON);
    }
    
}
```

Note that, strictly speaking, this is not a validation failure, since it's Jackson failing to parse the JSON early on. 

Alternatively, you can enable `DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL` in the Jackson configuration:

```yaml
jackson:
    deserialization:
        readUnknownEnumValuesAsNull: true
```

So that Jackson doesn't throw an exception, then the `@NotNull` validation will trigger giving you a 400 bad request.
