### ISSUE TITLE
URL encoding is not propagating

### ISSUE THREAD

**Issue by lkonya** [micronaut-projects/micronaut-aws#32]
### Steps to Reproduce
1. Create project: `mn create-app aws-api-gateway-test --features aws-api-gateway`
2. Add a controller, with an endpoint that waits for a path param
```java
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.QueryValue;

@Controller
public class TestController {

    @Get("/books/{book}")
    public String book(String book) {
        return "{\"book\": \"" + book + "\"}";
    }
}
```
2. Run `./gradlew clean build && sam local start-api --template sam.yaml`
3. Call `http://127.0.0.1:3000/books/The%20Name%20of%20the%20Wind` or `http://127.0.0.1:3000/books/The Name of the Wind`

Example project can be checked out from here: https://github.com/lkonya/micronaut-aws-api-gateway-test.git

### Expected Behaviour
HTTP 200 - successfully decode URL path
```
{
    "book": "The Name of the Wind"
}
```

### Actual Behaviour
HTTP 500 - Internal Server Error
Server:
```java
com.amazonaws.serverless.exceptions.InvalidRequestEventException: Invalid Request: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Wind
        at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:123)
        at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:48)
        at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:204)
        at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxyStream(AbstractLambdaContainerHandler.java:239)
        at aws.api.gateway.test.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
        at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
        at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Wind
        at java.net.URI.create(URI.java:852)
        at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getUri(MicronautAwsProxyRequest.java:174)
        at io.micronaut.http.HttpRequest.getPath(HttpRequest.java:85)
        at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:79)
        ... 15 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Wind
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 18 more
END RequestId: 65a9e328-1710-402a-ad10-f3515714416b
REPORT RequestId: 65a9e328-1710-402a-ad10-f3515714416b  Duration: 186.98 ms     Billed Duration: 200 ms Memory Size: 512 MB     Max Memory Used: 34 MB  
[2019-04-19 09:32:28.966] " + NO_REQUEST_ID + " INFO i.m.f.a.p.AbstractLambdaContainerHandler - Starting Lambda Container Handler 
[2019-04-19 09:32:29.086] " + NO_REQUEST_ID + " INFO i.m.c.e.DefaultEnvironment - Established active environments: [function] 
com.amazonaws.serverless.exceptions.InvalidRequestEventException: Invalid Request: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Windr    at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:123)r at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:48)r       at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:204)r       at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxyStream(AbstractLambdaContainerHandler.java:239)r      at aws.api.gateway.test.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:24)r at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)r      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)r       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)r    at java.lang.reflect.Method.invoke(Method.java:498)r    at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)r     at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)r    at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)r   at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)r        at java.lang.Class.forName0(Native Method)r  at java.lang.Class.forName(Class.java:348)r     at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)rCaused by: java.lang.IllegalArgumentException: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Windr   at java.net.URI.create(URI.java:852)r   at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getUri(MicronautAwsProxyRequest.java:174)r       at io.micronaut.http.HttpRequest.getPath(HttpRequest.java:85)r  at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:79)r       ... 15 common frames omittedrCaused by: java.net.URISyntaxException: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Windr  at java.net.URI$Parser.fail(URI.java:2848)r     at java.net.URI$Parser.checkChars(URI.java:3021)r       at java.net.URI$Parser.parseHierarchical(URI.java:3105)r     at java.net.URI$Parser.parse(URI.java:3053)r    at java.net.URI.<init>(URI.java:588)r   at java.net.URI.create(URI.java:850)r   ... 18 common frames omittedr
com.amazonaws.serverless.exceptions.InvalidRequestEventException: Invalid Request: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Windr    at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:123)r at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:48)r       at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:204)r       at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxyStream(AbstractLambdaContainerHandler.java:239)r      at aws.api.gateway.test.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:24)r at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)r      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)r       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)r    at java.lang.reflect.Method.invoke(Method.java:498)r    at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)r     at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)r    at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)r   at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)r        at java.lang.Class.forName0(Native Method)r  at java.lang.Class.forName(Class.java:348)r     at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)rCaused by: java.lang.IllegalArgumentException: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Windr   at java.net.URI.create(URI.java:852)r   at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getUri(MicronautAwsProxyRequest.java:174)r       at io.micronaut.http.HttpRequest.getPath(HttpRequest.java:85)r  at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:79)r       ... 15 common frames omittedrCaused by: java.net.URISyntaxException: Illegal character in path at index 61: https://1234567890.execute-api.eu-central-1.amazonaws.com/The Name of the Windr  at java.net.URI$Parser.fail(URI.java:2848)r     at java.net.URI$Parser.checkChars(URI.java:3021)r       at java.net.URI$Parser.parseHierarchical(URI.java:3105)r     at java.net.URI$Parser.parse(URI.java:3053)r    at java.net.URI.<init>(URI.java:588)r   at java.net.URI.create(URI.java:850)r   ... 18 common frames omittedr
2019-04-19 11:32:31 No Content-Type given. Defaulting to 'application/json'.
2019-04-19 11:32:31 127.0.0.1 - - [19/Apr/2019 11:32:31] "GET /The%20Name%20of%20the%20Wind HTTP/1.1" 500 -
```

### Environment Information

- **Operating System**: MacOs Mojava version: 10.14.4
- **Micronaut Version:** 1.1.0
- **JDK Version:** 1.8.0_202

**Comment by lkonya** [comment]
It looks like a SAM local issue is related:
	- https://github.com/awslabs/aws-sam-cli/issues/771

**Comment by jameskleeh** [comment]
@lkonya I really have no idea, however how would it know the path is encoded or not? Shouldn't it be consistent either way?

**Comment by lkonya** [comment]
Yeah, the more I think about it, the more I realize, it isn't MN responsibility. Thank you @jameskleeh!
