### ISSUE TITLE
Micronaut+DynamoDB+GraalVM: Error while creating the image

### ISSUE THREAD

**Issue by mlaiboy** [micronaut-projects/micronaut-aws#454]
I created the project from the Project Generator of Micronaut framework. I have extended it to read items from DtnamoDB.

### Steps to Reproduce
Checkout https://github.com/mlaiboy/demo-native
Run ```docker-build.sh```

### Expected Behaviour
Just work.

### Actual Behaviour
It failing while creating native-image.

Step 19/24 : RUN /usr/lib/graalvm/bin/native-image --no-server -cp build/libs/demo-native-*-all.jar
 ---> Running in 0871b90d3e98
[demo-native:19]    classlist:  19,864.53 ms,  2.05 GB
[demo-native:19]        (cap):   1,422.31 ms,  2.05 GB
[demo-native:19]        setup:   5,061.26 ms,  2.05 GB
[demo-native:19]     (clinit):   2,475.20 ms,  2.34 GB
[demo-native:19]   (typeflow): 134,005.99 ms,  2.34 GB
[demo-native:19]    (objects):  66,521.24 ms,  2.34 GB
[demo-native:19]   (features):  11,446.93 ms,  2.34 GB
[demo-native:19]     analysis: 221,067.54 ms,  2.34 GB
Warning: Aborting stand-alone image build. com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(String, byte[], int, int, ProtectionDomain, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:756)
Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain): 
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
        at com.oracle.svm.reflect.ClassLoader_defineClass_c6c343b4d6dc22ca64eb2d8503b13ac9c340dcb3_2495.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.micronaut.core.reflect.ReflectionUtils.invokeMethod(ReflectionUtils.java:204)
        at io.micronaut.core.beans.ReflectionBeanMap.get(ReflectionBeanMap.java:89)
        at io.micronaut.core.beans.ReflectionBeanMap$1.getValue(ReflectionBeanMap.java:148)
        at sun.security.ssl.SSLSocketImpl$NotifyHandshakeThread.run(SSLSocketImpl.java:2740)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Aborting stand-alone image build. com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(String, byte[], int, int, ProtectionDomain, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:756)
Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain): 
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
        at com.oracle.svm.reflect.ClassLoader_defineClass_c6c343b4d6dc22ca64eb2d8503b13ac9c340dcb3_2495.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.micronaut.core.reflect.ReflectionUtils.invokeMethod(ReflectionUtils.java:204)
        at io.micronaut.core.beans.ReflectionBeanMap.get(ReflectionBeanMap.java:89)
        at io.micronaut.core.beans.ReflectionBeanMap$1.getValue(ReflectionBeanMap.java:148)
        at sun.security.ssl.SSLSocketImpl$NotifyHandshakeThread.run(SSLSocketImpl.java:2740)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

        at com.oracle.svm.hosted.FallbackFeature.reportFallback(FallbackFeature.java:209)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:219)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(String, byte[], int, int, ProtectionDomain, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:756)
Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain): 
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
        at com.oracle.svm.reflect.ClassLoader_defineClass_c6c343b4d6dc22ca64eb2d8503b13ac9c340dcb3_2495.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.micronaut.core.reflect.ReflectionUtils.invokeMethod(ReflectionUtils.java:204)
        at io.micronaut.core.beans.ReflectionBeanMap.get(ReflectionBeanMap.java:89)
        at io.micronaut.core.beans.ReflectionBeanMap$1.getValue(ReflectionBeanMap.java:148)
        at sun.security.ssl.SSLSocketImpl$NotifyHandshakeThread.run(SSLSocketImpl.java:2740)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:750)
        ... 7 more
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(String, byte[], int, int, ProtectionDomain, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:183)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:397)
        at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:116)
        at org.graalvm.compiler.java.BytecodeParser.lookupMethodInPool(BytecodeParser.java:4323)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.lookupMethodInPool(SharedGraphBuilderPhase.java:107)
        at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4317)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1800)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5339)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:225)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:352)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:373)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        ... 4 more
[demo-native:83]    classlist:   7,197.54 ms,  1.09 GB
[demo-native:83]        (cap):   1,387.67 ms,  1.09 GB
[demo-native:83]        setup:   5,144.75 ms,  1.09 GB
[demo-native:83]     (clinit):     224.17 ms,  1.49 GB
[demo-native:83]   (typeflow):  11,502.88 ms,  1.49 GB
[demo-native:83]    (objects):   5,062.13 ms,  1.49 GB
[demo-native:83]   (features):     301.34 ms,  1.49 GB
[demo-native:83]     analysis:  17,317.81 ms,  1.49 GB
[demo-native:83]     universe:     636.23 ms,  1.55 GB
[demo-native:83]      (parse):   4,155.30 ms,  1.55 GB
[demo-native:83]     (inline):   2,263.47 ms,  1.56 GB
[demo-native:83]    (compile):  22,364.54 ms,  1.84 GB
[demo-native:83]      compile:  29,257.24 ms,  1.84 GB
[demo-native:83]        image:     878.94 ms,  1.84 GB
[demo-native:83]        write:     208.65 ms,  1.84 GB
[demo-native:83]      [total]:  61,298.43 ms,  1.84 GB
Warning: Image 'demo-native' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
Removing intermediate container 0871b90d3e98

Environment Information
Operating System: osx 11.15
Micronaut Version: 2.0.0
JDK Version: jdk8
Example Application
### TODO: https://github.com/mlaiboy/demo-native
Here is the discussion that I had with @graemerocher
[twitter](https://twitter.com/graemerocher/status/1288728717620060160)

**Comment by ilopmar** [comment]
@mlaiboy Adding `--report-unsupported-elements-at-runtime` makes it work. Please keep in mind that the usage of that flag is discouraged and should be avoided.

I'll report an issue to GraalVM.

**Comment by ilopmar** [comment]
https://github.com/oracle/graal/issues/2758

**Comment by mlaiboy** [comment]
Thanks a lot. It did fix the issue.
