### ISSUE TITLE
FileNotFoundException error getting public host name from:http://169.254.169.254/latest/meta-data/publicHostname

### ISSUE THREAD

**Issue by dgbmariano** [micronaut-projects/micronaut-aws#497]
This issue is related to this issue: https://github.com/micronaut-projects/micronaut-core/issues/2934.
Our app is hosted in Amazon and every time that we start a pod we get two errors:

```
error getting public host name from:http://169.254.169.254/latest/meta-data/publicHostname


java.io.FileNotFoundException: http://169.254.169.254/latest/meta-data/public-hostname
 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
 	at io.micronaut.discovery.cloud.aws.AmazonComputeInstanceMetadataResolver.readEc2MetadataUrl(AmazonComputeInstanceMetadataResolver.java:180)
 	at io.micronaut.discovery.cloud.aws.AmazonComputeInstanceMetadataResolver.resolve(AmazonComputeInstanceMetadataResolver.java:113)
 	at io.micronaut.grpc.server.GrpcEmbeddedServer.lambda$start$1(GrpcEmbeddedServer.java:166)
 	at java.util.Optional.ifPresent(Optional.java:159)
 	at io.micronaut.grpc.server.GrpcEmbeddedServer.start(GrpcEmbeddedServer.java:162)
 	at io.micronaut.grpc.server.GrpcEmbeddedServerListener.onApplicationEvent(GrpcEmbeddedServerListener.java:59)
 	at io.micronaut.grpc.server.GrpcEmbeddedServerListener.onApplicationEvent(GrpcEmbeddedServerListener.java:37) 
	at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1302)
 	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1287)
 	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:495)
 	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:341)
 	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:110)
 	at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:70)
 	at java.util.Optional.ifPresent(Optional.java:159)
 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
```

And:
```

java.io.FileNotFoundException: http://169.254.169.254/latest/meta-data//network/interfaces/macs/XX:XX:XX:XX:XX:XX/public-ipv4s/
 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
 	at io.micronaut.discovery.cloud.aws.AmazonComputeInstanceMetadataResolver.readEc2MetadataUrl(AmazonComputeInstanceMetadataResolver.java:180)
 	at io.micronaut.discovery.cloud.aws.AmazonComputeInstanceMetadataResolver.resolve(AmazonComputeInstanceMetadataResolver.java:128)
 	at io.micronaut.grpc.server.GrpcEmbeddedServer.lambda$start$1(GrpcEmbeddedServer.java:166) 	at java.util.Optional.ifPresent(Optional.java:159)
 	at io.micronaut.grpc.server.GrpcEmbeddedServer.start(GrpcEmbeddedServer.java:162)
 	at io.micronaut.grpc.server.GrpcEmbeddedServerListener.onApplicationEvent(GrpcEmbeddedServerListener.java:59)
 	at io.micronaut.grpc.server.GrpcEmbeddedServerListener.onApplicationEvent(GrpcEmbeddedServerListener.java:37)
 	at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1302)
 	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1287)
 	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:495)
 	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:341)
 	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:110)
 	at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:70)
 	at java.util.Optional.ifPresent(Optional.java:159)
 	at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
```
For the second error, I believe that the cause is because of the val `metadataUrl` that is `url + "/latest/meta-data/"` defined in the file `AmazonMetadataConfiguration.java` but in the file `AmazonComputeInstanceMetadataResolver.java` we have:
```
String vpcId = readEc2MetadataUrl(new URL(ec2InstanceMetadataURL + "/network/interfaces/macs/" + macAddress + "/vpc-id/"), CONNECTION_TIMEOUT_IN_MILLS, READ_TIMEOUT_IN_MILLS);
```
Causing the double // in the path. I've tried to make the metadataUrl be `url + "/latest/meta-data` but broke other things, so maybe the way is to fix the paths in `AmazonComputeInstanceMetadataResolver.java`. 

Thanks.

**Comment by etnishiyama** [comment]
We have the same issue here. Do we have any update on this?

**Comment by ttzn** [comment]
If you could provide a minimal example set up that we can reproduce (with dependency versions), it would increase the likelihood that somebody contributes a fix.

**Comment by pgressa** [comment]
@etnishiyama @dgbmariano could you please share some example so I can replicate the issue and provide proper fix. Or maybe describe in more depth the context of the issue. I understand that it's happening in K8s only?

**Comment by dgbmariano** [comment]
Sorry for not updating. I've tried to reproduce locally but I couldn't. The maximum that I could get I described in the description. The enviromnents are: [k8s, cloud, ec2, prod]. 
Also, we upgraded the micronaut version some months ago and we are not getting this error anymore. Maybe we could close this issue now. Sorry for not updating!

**Comment by pgressa** [comment]
Hi @dgbmariano no worries. Ok so I'm going to close this issue now. If you or @etnishiyama will experience this issue once again, please open new issue, ideally with simple example in github. To easily create reproducer in github use the launcher https://micronaut.io/launch/ .. it has the button push-to-github and even the dekorate feature for k8s deployment.
