### ISSUE TITLE
micronaut-aws-parameter-store exception in native execution

### ISSUE THREAD

**Issue by jmansiya** [micronaut-projects/micronaut-aws#917]
Hi, I have an exception when I execute my AWS Lambda funcion in Native using this library:

```
  <groupId>io.micronaut.aws</groupId>      
   <artifactId>micronaut-aws-parameter-store</artifactId> 
```

The exception is:

```
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.discovery.aws.parameterstore.AWSParameterStoreConfigClient]

Path Taken: new DistributedPropertySourceLocator([ConfigurationClient configurationClient],Duration readTimeout) --> new DefaultCompositeConfigurationClient([ConfigurationClient[] configurationClients]) --> new AWSParameterStoreConfigClient([AWSClientConfiguration awsConfiguration],AWSParameterStoreConfiguration awsParameterStoreConfiguration,ApplicationConfiguration applicationConfiguration,AWSParameterQueryProvider queryProvider,Route53ClientDiscoveryConfiguration route53ClientDiscoveryConfiguration)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1925)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2679)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2665)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2337)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2311)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1245)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
        at io.micronaut.discovery.aws.parameterstore.$AWSParameterStoreConfigClientDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3022)
        at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2923)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1045)
        at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$9(AbstractBeanDefinition.java:1143)
        at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1822)
        at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1138)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:987)
        at io.micronaut.discovery.config.$DefaultCompositeConfigurationClientDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2679)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2665)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2337)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2311)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1245)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
        at io.micronaut.discovery.client.config.$DistributedPropertySourceLocatorDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2679)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2665)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2337)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2311)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:733)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.resolveBootstrapPropertySourceLocator(DefaultApplicationContext.java:736)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:711)
        at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:392)
        at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:254)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:697)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:665)
        at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:213)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:165)
        at io.micronaut.function.executor.AbstractExecutor.startEnvironment(AbstractExecutor.java:125)
        at io.micronaut.function.aws.MicronautRequestHandler.buildApplicationContext(MicronautRequestHandler.java:163)
        at io.micronaut.function.aws.MicronautRequestHandler.<init>(MicronautRequestHandler.java:60)
        at com.example.LambdaHandler.<init>(LambdaHandler.java:14)
        at com.example.MicronautApplication.createRequestHandler(MicronautApplication.java:27)
        at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.createHandler(AbstractMicronautLambdaRuntime.java:192)
        at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:313)
        at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:129)
        at com.example.MicronautApplication.main(MicronautApplication.java:18)
Caused by: java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
        at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:143)
        at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:137)
        at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:100)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:80)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at io.micronaut.aws.sdk.v1.AWSClientConfiguration.<init>(AWSClientConfiguration.java:36)
        at io.micronaut.aws.sdk.v1.$AWSClientConfigurationDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
        ... 47 more
Caused by: java.lang.IllegalArgumentException
        at com.amazonaws.internal.config.InternalConfig.loadfrom(InternalConfig.java:249)
        at com.amazonaws.internal.config.InternalConfig.load(InternalConfig.java:263)
Request loop failed with: Error instantiating bean of type  [io.micronaut.discovery.aws.parameterstore.AWSParameterStoreConfigClient]

Path Taken: new DistributedPropertySourceLocator([ConfigurationClient configurationClient],Duration readTimeout) --> new DefaultCompositeConfigurationClient([ConfigurationClient[] configurationClients]) --> new AWSParameterStoreConfigClient([AWSClientConfiguration awsConfiguration],AWSParameterStoreConfiguration awsParameterStoreConfiguration,ApplicationConfiguration applicationConfiguration,AWSParameterQueryProvider queryProvider,Route53ClientDiscoveryConfiguration route53ClientDiscoveryConfiguration)
        at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:336)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        ... 56 more
```

You can test this error with this example: [https://github.com/jmansiya/micronaut-ssm-demo](example).
To reproduce the error only need to do:
Execute: deploy.sh

```
sam local invoke -t templateNative.yaml -e event.json
```

This AWS Lambda works correctly without native application.

Thanks in advance!

**Comment by pgressa** [comment]
@jmansiya since #944 with 2.4.0-SNAPSHOT version Micronaut uses aws sdk that has native support included. See this example app https://github.com/micronaut-graal-tests/micronaut-aws-sdk2-graal/tree/2.4.x_paramstore . Please gives us feedback whether everything now works for you. Thanks

**Comment by jmansiya** [comment]
Hi, sorry I've been a few days without internet. I tried this but I have the same exception. I've push the changes to use 2.4.0-snapshot in the  https://github.com/jmansiya/micronaut-ssm-demo repo.

Do I have to create a new ticket??
Thanks!!

**Comment by ilopmar** [comment]
@jmansiya I'm not able to try your sample app because errors in credentials. In any case I've seen that you are not using the right version for all micronaut-aws depedencies. 
Can you please tried adding `<micronaut.aws.version>2.4.0-SNAPSHOT</micronaut.aws.version>` to the `properties` section in your bom and try it again?

In the mean time, as @pgressa said, we have included the aws v2 sdk that supports GraalVM and we have a test application for this: https://github.com/micronaut-graal-tests/micronaut-aws-sdk2-graal/tree/2.4.x_paramstore. I'm in the middle of modifying a few things in the app to integrate it with our GraalVM CI, but everything seems to be working at this moment.

**Comment by ilopmar** [comment]
@jmansiya I've updated [our test application](https://github.com/micronaut-graal-tests/micronaut-aws-sdk2-graal/tree/2.4.x_paramstore) and it works as a native image locally and when deploying it to AWS Lambda. If you have issues with your app, please compare it with ours.

**Comment by lkanth4u** [comment]
Running into the same exception (execute my AWS Lambda function in Native); but I am trying to run aws lambda stepfunctions. Any references on how to execute aws-java-sdk-stepfunctions (1.12.270 version i tried).
